version: '3'

services:
  drf:
    build: .
    volumes:
      - .:/app
    ports:
      - 8091:80
    environment:
      - SEMANTICDATA_DEBUG=TRUE
      - SEMANTICDATA_LOGLEVEL=DEBUG
      - SEMANTICDATA_DJANGO_KEY=anweijfnvwoejvniejnvfwvijnf
